name: cahrity_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #============ network client ==============
  dio: ^5.4.0
  #============ state management BloC=========
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  #============ svg assets ===============
  flutter_svg: ^2.0.9
  #============ dependency injection ===============
  get_it: ^7.6.4
  #============= check internet connection=========
  internet_connection_checker: ^1.0.0+1
  #============ responsive for ui and fonts =========
  flutter_screenutil: ^5.9.0
  #========= services logging ===========
  logger: ^2.0.2+1
  # flutter_dotenv: ^5.1.0
  #========= local storage & cach ===========
  shared_preferences: ^2.2.2
  flutter_cache_manager: ^3.3.1

  #============ toast and snakbar =============
  bot_toast: ^4.1.3
  awesome_snackbar_content: ^0.1.3
  #============ localization and format =============
  intl: ^0.18.1
  easy_localization: ^3.0.3
  #============ routing of app =============
  go_router: ^13.1.0

  #============ for push notifications =============
  flutter_local_notifications: ^16.2.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.8
  # ================================================

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_form_builder: ^9.2.0
  pinput: ^3.0.1
  flutter_story: ^1.0.1
  injectable: ^2.3.2
  retrofit: ^4.0.3  
  pretty_dio_logger: ^1.3.1
  cached_network_image: ^3.3.1
  adaptive_shimmer: ^0.0.8
  url_launcher: ^6.2.5
  path: ^1.9.0
  permission_handler: ^11.3.0
  font_awesome_flutter: ^10.7.0
  carousel_slider: ^4.2.1
  easy_stepper: ^0.8.3
  # ================================================

dependency_overrides:
  video_player: ^2.8.2
  youtube_player_flutter: ^8.1.2
  chewie: ^1.7.4
  file_picker: ^6.2.0

  #===================================================
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  freezed: ^2.4.6
  json_serializable: ^6.7.1

  build_runner: ^2.4.8
  retrofit_generator: ^8.0.6
  injectable_generator: ^2.4.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/app_icon.png"
  icon_background_color: "#ffffff"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  fullscreen: true
  android_12:
    icon_background_color: "#FFFFFF00"
    fullscreen: false

flutter:
  uses-material-design: true
  assets:
    - assets/translation/
    - assets/svg/
    - assets/png/
    - assets/config/
    - pubspec.yaml
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: true
          checked: false
          constructor: ""
          create_factory: true
          create_field_map: false
          create_per_field_to_json: false
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
