// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDRnf2VqRvLNFI6Zm8WVQItXuB_MJePGHk',
//     appId: '1:378789892144:web:41543af6a50b0f19255df5',
//     messagingSenderId: '378789892144',
//     projectId: 'sharjahaward-1070d',
//     authDomain: 'sharjahaward-1070d.firebaseapp.com',
//     storageBucket: 'sharjahaward-1070d.appspot.com',
//     measurementId: 'G-0PX96WYD8V',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDNfR9yj3ailUMddqCuE26S1-uBNQlNAPE',
//     appId: '1:378789892144:android:fd54f6fa1f925c3f255df5',
//     messagingSenderId: '378789892144',
//     projectId: 'sharjahaward-1070d',
//     storageBucket: 'sharjahaward-1070d.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBld4Y1DsRas0UcG0b4sUylO3UnvLywwE8',
//     appId: '1:378789892144:ios:59781cd0ba68dc58255df5',
//     messagingSenderId: '378789892144',
//     projectId: 'sharjahaward-1070d',
//     storageBucket: 'sharjahaward-1070d.appspot.com',
//     iosBundleId: 'com.example.sharjahApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBld4Y1DsRas0UcG0b4sUylO3UnvLywwE8',
//     appId: '1:378789892144:ios:59781cd0ba68dc58255df5',
//     messagingSenderId: '378789892144',
//     projectId: 'sharjahaward-1070d',
//     storageBucket: 'sharjahaward-1070d.appspot.com',
//     iosBundleId: 'com.example.sharjahApp',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDRnf2VqRvLNFI6Zm8WVQItXuB_MJePGHk',
//     appId: '1:378789892144:web:7ea99b47315058eb255df5',
//     messagingSenderId: '378789892144',
//     projectId: 'sharjahaward-1070d',
//     authDomain: 'sharjahaward-1070d.firebaseapp.com',
//     storageBucket: 'sharjahaward-1070d.appspot.com',
//     measurementId: 'G-K2W2S7B4ZB',
//   );
// }
